### ISSUE TITLE
Getting error: Unable to locate package rg

### ISSUE THREAD

**Issue by utkarshborawake** [x543g/E-Forensics#1]
/E-Forensics$ fish E-forensics.fish spam.eml
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package rg
fish: Unknown command: rg
E-forensics.fish (line 1): 
rg -N '^Subject: ' "$argv[1]" |cut -f2 -d ":" |sed 's/^ //'
^
in command substitution
	called on line 42 of file E-forensics.fish
E-forensics.fish: Unknown error while evaluating command substitution
file is not a valid type, exiting...
ubu@u:~/E-Forensics$ fish E-forensics.fish /spam.eml
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package rg
fish: Unknown command: rg
E-forensics.fish (line 1): 
rg -N '^Subject: ' "$argv[1]" |cut -f2 -d ":" |sed 's/^ //'
^
in command substitution
	called on line 42 of file E-forensics.fish
E-forensics.fish: Unknown error while evaluating command substitution
file is not a valid type, exiting...

**Comment by x543g** [comment]
Evening. I added an update for the deps, instead of "rg" it's "ripgrep", which alias is rg. It should work now.

**Comment by x543g** [comment]
@utkarshborawake closing it out, if it still persists, please reopen.
